name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.STO2024_CREDS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.STO2024_SUB }}
        resourceGroupName: ${{ secrets.STO2024_RG }}
        template: ./bicep/storage.bicep
        parameters: 'storagePrefix=stkhlm2024 storageSKU=Standard_LRS'
        failOnStdErr: false
